compatibility_date = "2024-12-16"
account_id = "2abd5f3a5cdcf01e98291c0a7a1f47e4"

name = "dbot"
workers_dev = true
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
minify = false

[observability.logs]
enabled = true
