compatibility_date = "2025-04-22"
account_id = "2abd5f3a5cdcf01e98291c0a7a1f47e4"

name = "dbot"
workers_dev = true
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
minify = false

[placement]
mode = "smart"

[observability.logs]
enabled = true
