/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/types.d.ts --include-runtime false` (hash: 1f2f91a7d0563adf94140f5240cca54f)
declare namespace Cloudflare {
  interface Env {
    DISCORD_TOKEN: SecretsStoreSecret;
    SYNC_TOKEN: SecretsStoreSecret;
    TURSO_AUTH_TOKEN: SecretsStoreSecret;
    TURSO_DATABASE_URL: SecretsStoreSecret;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'DISCORD_TOKEN'
        | 'SYNC_TOKEN'
        | 'TURSO_DATABASE_URL'
        | 'TURSO_AUTH_TOKEN'
      >
    > {}
