/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/types.d.ts --include-runtime false` (hash: 8c0df96e79cc868f5c0211c4cc6ede8c)
declare namespace Cloudflare {
  interface Env {
    DISCORD_TOKEN: SecretsStoreSecret;
    SYNC_TOKEN: SecretsStoreSecret;
    TURSO_AUTH_TOKEN: SecretsStoreSecret;
    TURSO_DATABASE_URL: SecretsStoreSecret;
  }
}
interface Env extends Cloudflare.Env {}
