/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/types.d.ts --include-runtime false` (hash: 83406a3f7264283c1e749bbae9188c92)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface Env {
    DISCORD_TOKEN: SecretsStoreSecret;
    SYNC_TOKEN: SecretsStoreSecret;
    TURSO_AUTH_TOKEN: SecretsStoreSecret;
    TURSO_DATABASE_URL: SecretsStoreSecret;
  }
}
interface Env extends Cloudflare.Env {}
